slice_name: avg_ox
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 22__table
  extra_form_data: {}
  granularity_sqla: timestamp
  header_font_size: 0.4
  metric:
    aggregate: AVG
    column:
      certification_details: null
      certified_by: null
      column_name: saturacao_oxigenio
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 745
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: AVG(saturacao_oxigenio)
    optionName: metric_ghydibs0h4_a1yr1yycukt
    sqlExpression: null
  slice_id: 83
  subheader: SpO2
  subheader_font_size: 0.2
  time_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 51aa377c-9531-4f31-8d21-54e1a72dccdd
version: 1.0.0
dataset_uuid: 43aa5125-1976-454a-a419-ce896fa8abdd
