slice_name: kpi_avgidade
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 22__table
  extra_form_data: {}
  granularity_sqla: timestamp
  header_font_size: 0.4
  metric:
    aggregate: AVG
    column:
      certification_details: null
      certified_by: null
      column_name: idade
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 737
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: AVG(idade)
    optionName: metric_5rjeo6lykfv_a13ljnqm7kj
    sqlExpression: null
  slice_id: 84
  subheader: anos
  subheader_font_size: 0.3
  time_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: b3d4305b-37e7-4c18-96ff-ffc1edc3e987
version: 1.0.0
dataset_uuid: 43aa5125-1976-454a-a419-ce896fa8abdd
