slice_name: kpi_avgtemp
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 22__table
  extra_form_data: {}
  granularity_sqla: timestamp
  header_font_size: 0.4
  metric:
    aggregate: AVG
    column:
      certification_details: null
      certified_by: null
      column_name: temperatura
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 743
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: AVG(temperatura)
    optionName: metric_tmafybqk7z_zq53wjcrl7
    sqlExpression: null
  slice_id: 82
  subheader: "\xBAC"
  subheader_font_size: 0.3
  time_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: ec7ef011-8ad0-4a9d-b094-746da761020a
version: 1.0.0
dataset_uuid: 43aa5125-1976-454a-a419-ce896fa8abdd
