slice_name: sum_passos_barchart1
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  datasource: 22__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  granularity_sqla: timestamp
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: passos
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 751
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(passos)
    optionName: metric_5w63l13ukam_u0x16eatvyo
    sqlExpression: null
  only_total: true
  order_desc: true
  rich_tooltip: false
  row_limit: 10000
  slice_id: 79
  stack: false
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  tooltipTimeFormat: '%d/%m/%Y'
  viz_type: echarts_timeseries_bar
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
cache_timeout: null
uuid: 1230095d-6db2-4bf4-be49-c92055c5673b
version: 1.0.0
dataset_uuid: 43aa5125-1976-454a-a419-ce896fa8abdd
